### ISSUE TITLE
Questions about the app functionality and layout

### ISSUE THREAD

**Issue by ayushi-agrawal-gladstone** [gladstone-institutes/Interactive-Enrichment-Analysis#20]
1. In the launched RShiny app, when I select the Mm_20231016.RData database and then select the provided E-GEOD-30573.csv dataset, the "Choose organism" dropdown is "human". Screenshot below. Is this expected? Shouldn't it auto populate based on the database that was picked and be "mouse" and not "human" in this scenario? <img width="700" alt="1" src="https://github.com/gladstone-institutes/Interactive-Enrichment-Analysis/assets/88406934/616fd8a3-dc1f-4d5c-8f9f-c7f4a0691e74">
2. For the Mm_20231016.RData database and E-GEOD-30573.csv dataset, the dot plot and concept network in the results tab shows an error. Is this expected? Also, do you think it might be useful to handle such errors in the background and show a message like "An error has occurred while running this operation. Contact <point_of_contact> for further assistance." ? I can work on adding this functionality.
    <img width="200" alt="2_2" src="https://github.com/gladstone-institutes/Interactive-Enrichment-Analysis/assets/88406934/b88af784-7be2-4de5-ac19-ad8c0b87877e"> <img width="180" alt="2_1" src="https://github.com/gladstone-institutes/Interactive-Enrichment-Analysis/assets/88406934/6343741f-9d27-449c-9f91-d6c0ca06dd6d">

3. The “Let’s go!” button is on the left menu bar. After selecting the database and dataset, it is not immediately intuitive to look for that button. A message to ask the user to click the button would be helpful. Placing the button on the screen and not just in the bar might help if the menu bar is closed and will also be easier to find.   

4. For the Hs_20231016.RData database; E-GEOD-30573.csv dataset and default options, I have a few questions about the results screen:

    4a. There is a collapsible "Summary" text box with blank fields. Should this be removed? 

    4b. In the results tab, when "pfocr_hs_20231016" database is selected, the PFOCR image is broken. <kbd><img width="220" alt="4_b" src="https://github.com/gladstone-institutes/Interactive-Enrichment-Analysis/assets/88406934/c6293664-412a-419a-b423-67c8efb64d34"></kbd>

    4c. In the results tab, when "pfocr_hs_20231016" database is selected, the names of pathways are overlapping in the "Choose a plot type for top results:" for most of the plots. 
<kbd><img width="220" alt="4_c" src="https://github.com/gladstone-institutes/Interactive-Enrichment-Analysis/assets/88406934/7af991a3-7e13-46d2-8dd0-965ec940da6d"></kbd>

    4d. In the results tab, when"pfocr_hs_20231016" database is selected, in the Concept network plot in the results tab, the dot sizes are hidden as the plot options overlap the dot sizes. 
<kbd><img width="320" alt="4_d" src="https://github.com/gladstone-institutes/Interactive-Enrichment-Analysis/assets/88406934/56a9ba3e-9eb1-46c1-a709-b89be761be41"></kbd>

**Comment by AlexanderPico** [comment]
Thanks for the thorough review!

1. I don't think the code performs auto-populate based on db selection. I think it just specifies human as default. Also, the dataset is human in this use case.
2. I definitely don't want to be a point of contact for errors! :) I think R error messages are fine for this application.
3. I think the left bar is the right place. The user can continue to tweak multiple defaults, so it is impossible to know when they are ready. Placing the button in the config UI would then cause confusion. Not a strong opinion, but also probably not worth dev time.
4a. Not sure. Will have to check a few cases.
4b. Fixed!
4c. Spacing controls are below figure. Guessing these for all cases is difficult.
4d. That plot is pretty useless unless it's for a handful of nodes, in which case it looks fine. So, it's okay.

**Comment by AlexanderPico** [comment]
4a. Oh yeah. That's just a static file. I was probably planning to dynamically update it per run, but never did. I've removed the section.

**Comment by AlexanderPico** [comment]
If we decide to publish this app, then some of your points should go into separate feature tickets:
1. Improving detection and messaging of errors and edge cases
2. Reviewing plot types and default params
