### ISSUE TITLE
Bar plot labels missing in Chrome 116 for Kristina

### ISSUE THREAD

**Issue by AlexanderPico** [gladstone-institutes/Interactive-Enrichment-Analysis#23]
I can't reproduce in Chrome 117 or FF.

**Comment by khanspers** [comment]
Updated to Chrome 119.0.6045.105 (Official Build), updated RStudio to latest => still the same issue in Chrome. Works in FF. The png in Chrome is missing the plot labels.

**Comment by khanspers** [comment]
Update: Michela tested this and labels appeared as expected.

**Comment by khanspers** [comment]
Bar plot labels are back!! Not sure what changed.
