### ISSUE TITLE
Unable to run analysis, app gets stuck 

### ISSUE THREAD

**Issue by marianaago** [gladstone-institutes/Interactive-Enrichment-Analysis#26]
Hi, 

I have been trying to run the analysis using this file [EctrlvEKD.csv](https://github.com/gladstone-institutes/Interactive-Enrichment-Analysis/files/14816531/EctrlvEKD.csv) against the provided human database. However, the analysis gets stuck at step 3:

![image](https://github.com/gladstone-institutes/Interactive-Enrichment-Analysis/assets/20342519/a509560e-5709-4dda-a366-954f71e000b9)

This also happens if I run the app using one of the example files.
I copied the R studio console log into a word file, attached here 
[errorlog_IEA.docx](https://github.com/gladstone-institutes/Interactive-Enrichment-Analysis/files/14816554/errorlog_IEA.docx)

Any help would be appreciated :) 

Thanks a lot in advance,

Mariana

**Comment by marianaago** [comment]
Update: I have been able to run it once but now I am facing the same issue as before, every time I try to run the analysis it gets stuck and I get the following error:

Warning: Error in grDevices::pdf: cannot open file '..//../shiny_result/output/20240331_192139/EctrlvEKD_test/gsea/plots/EctrlvEKD_test_go_hs_20240315_gsea_dot_gr.pdf'

As if the program cannot access the shiny_result folder. Is there a better way to save the Interactive-Enrichment-Analysis-main folder? Right now I have it saved in an external hard drive where I store all the data from an RNAseq experiment. Not sure if running the app in this way is causing the issue? 

Thanks in advance,

Mariana

**Comment by lau99-0** [comment]
Hello, same problem here. Did you figure it out? 

thanks.

**Comment by AlexanderPico** [comment]
I haven't tried with an external harddrive. That could indeed be the issue. Fortuntely, it's easy to fix... even after the fact.

For future runs, you can set your working directory in RStudio to a different location prior to running the launch script (the copy/paste code).

For past runs, you can copy or move the folders under "Interactive-Enrichment-Analysis" to another location on your main HD. All the data and code are in the same folder, so you can then navigate to the new location in RStudio and run it from there.

Let me know if that fixes it.
