### ISSUE TITLE
Failed to add other species database

### ISSUE THREAD

**Issue by Jimmyishungry** [gladstone-institutes/Interactive-Enrichment-Analysis#27]
when upload Drosophila wikipathways gmt file, building new database process is too long and seems never get ready.

**Comment by AlexanderPico** [comment]
When I try to make a database from Drosophila wikipathways gmt, it appears to complete and generate an .RData file, but then the file causes this error:

```
Warning: Error in eval: object 'wikipathways' not found
  101: eval [<text>#1]
  100: eval
   98: getDatabaseSet [/Users/apico/git/gladstone-institutes/Interactive-Enrichment-Analysis/shiny_run/app/server.R#70]
   97: renderTable [/Users/apico/git/gladstone-institutes/Interactive-Enrichment-Analysis/shiny_run/app/server.R#139]
   96: func
   83: renderFunc
   82: output$db.list
    1: runApp
```

I'll look into solving this bug first. If I can make an .RData that works, then I'll share it with you and you can also try the updated code.

**Comment by AlexanderPico** [comment]
Here you go. This is a built database file: https://www.dropbox.com/scl/fi/xsu5bjryp92oan8qrqgr7/Dm_WP_20240710.RData?rlkey=9fsn6uk1a59c5aa818u337axo&dl=0

The "trick" was to rename the gmt file before processing it. The code assumes WikiPathways GMT files will be named like wp_dm_20240710.gmt. So, I renamed it and it all worked. 

I will next fix the code to not require this manual renaming. But you may still have a different bug.  If so, please reopen and let me know.
